//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public int Categories_ID { get; set; }
        public Nullable<int> SubCategories_ID { get; set; }
        public string Assignment_Type { get; set; }
        public string Audio_File { get; set; }
        public string Assignment_Title { get; set; }
        public string Answer_One { get; set; }
        public string Answer_Two { get; set; }
        public string Answer_Three { get; set; }
        public string Answer_Four { get; set; }
        public string Answer_Five { get; set; }
        public string Answer_Six { get; set; }
        public string Correct_Answer { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
